version: '3.8'
services:
  savey_llm:
    platform: linux/amd64
    build: .
    container_name: savey_llm_worker
    restart: always
    volumes:
      - .:/app
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          memory: 2g

networks:
  dokploy-network:
    external: true